config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    mount Sidekiq::Web => "/sidekiq"

    root "amplifiers#index", as: :authenticated_root
    get 'amplifiers/new', to: 'amplifiers#new_amplifier', as: 'new_amplifier'

    resources :amplifiers do
      post 'create_conversation', on: :collection
      post 'create_custom_conversation', on: :collection
      post 'attachments', on: :collection
    end
  end

  unauthenticated :user do
    root "pages#about", as: :unauthenticated_root
  end

  get "about", to: "pages#about"
  resources :amplifier_prompts, only: [:index]
  get 'get_partial', to: 'amplifier_prompts#get_partial'
  post 'upload_url', to: 'amplifiers#upload_url', as: 'upload_url'
end

app/models/amplifier.rb
# == Schema Information
#
# Table name: amplifiers
#
#  id                :bigint           not null, primary key
#  client_id         :integer
#  title             :string
#  start_at          :datetime
#  state             :enum
#  user_id           :bigint
#  description       :text
#  amplifier_type_id :bigint
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class Amplifier < ApplicationRecord
  include AASM

  belongs_to :user
  belongs_to :amplifier_type
  has_many :amplifier_conversations, dependent: :destroy

  enum state: {
    draft: 'draft',
    published: 'published',
    archived: 'archived',
  }

  aasm column: :state, enum: true do
    state :draft, initial: true
    state :published
    state :archived

    # Define your events and transitions here
  end

  # Add any validations and associations here
end

app/models/amplifier_type.rb
# == Schema Information
#
# Table name: amplifier_types
#
#  id         :bigint           not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class AmplifierType < ApplicationRecord
  has_many :amplifiers, dependent: :delete_all
  has_many :amplifier_prompts, dependent: :delete_all
  has_many :amplifier_prompt_categories

  # Add any validations and associations here
end

app/controllers/amplifiers_controller.rb
class AmplifiersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_amplifier, only: [:destroy, :update, :edit]

  def index
    @amplifiers = current_user.amplifiers.order(created_at: :desc)
    @pagy, @amplifiers = pagy(@amplifiers)
  end

  def edit
    @conversation = AmplifierConversation.find_or_create_by(amplifier: @amplifier)
  end

  def new_amplifier
    @amplifier = current_user.amplifiers.create(user: current_user, title: "Untitled",
                                                amplifier_type: AmplifierType.find_by(title: "Unassigned"))
    @client = OpenAI::Client.new
    redirect_to edit_amplifier_path(@amplifier)
  end

  def update
    if @amplifier.update(amplifier_params)
      flash[:notice] = 'Amplifier successfully updated'
      respond_to do |format|
        format.html { head :no_content }
        format.turbo_stream
      end
    else
      flash.now[:alert] = 'Failed to update amplifier'
      render 'edit'
    end
  end

  def destroy
    if @amplifier.destroy
      # Fetch the item from the next page if available
      pagy, _ = pagy(current_user.amplifiers.order(created_at: :desc))
      next_item = current_user.amplifiers.order(created_at: :desc).offset(pagy.offset + pagy.items).first

      # Update the current list of amplifiers
      @pagy, @amplifiers = pagy(current_user.amplifiers.order(created_at: :desc))

      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.remove("amplifier_#{@amplifier.id}"),
            (if next_item
               turbo_stream.append("amplifiers_list", partial: "amplifier",
                                                      locals: { amplifier: next_item })
             end),
            turbo_stream.replace("pagination", partial: "pagination", locals: { pagy: @pagy }),
          ].compact
        end
        format.html { redirect_to amplifiers_path, notice: 'Amplifier successfully deleted.' }
      end
    else
      flash[:alert] = "There was an error deleting the amplifier."
      redirect_to amplifiers_path
    end
  end

  def create_custom_conversation
    conversation = AmplifierConversation.find(params[:conversation_id])

    CreateCustomConversationJob.perform_later(
      params[:conversation_id],
      params[:category_id],
      custom_inputs_params.to_h,
      :human
    )

    render turbo_stream: [
      turbo_stream.replace(
        "message_container",
        partial: "amplifier_conversations/messages",
        locals: { message: OpenStruct.new(content: "Generating...", speaker: "Assistant"), conversation: conversation, custom_conversation: true }
      )
    ]
  end

  def upload_url
    @conversation = AmplifierConversation.find(params[:amplifier_conversation_id])
    @attachment_url = @conversation.attachments.new(url: params[:attachment][:url])

    if @attachment_url.save!
      ProcessUploadedUrlJob.perform_later(@attachment_url.id)
    end
  end


  def create_conversation
    result = CreateConversationOrganizer.call(
      conversation_id: message_params[:conversation_id],
      content: message_params[:content],
      speaker: :human
    )
    if result.success?
      render turbo_stream: [
        turbo_stream.replace(
          "message_container",
          partial: "amplifier_conversations/messages",
          locals: { message: result.message, conversation: result.conversation }
        ),
        turbo_stream.replace(
          "conversation_form",
          partial: "amplifiers/form_conversation",
          locals: {
            amplifier: result.conversation.amplifier, conversation: result.conversation,
            message: "",
            user_id: current_user.id
          }
        ),
      ]
    end
  end

  def attachments
    @attachment = Attachment.new(amplifier_conversation_id: params[:amplifier_conversation_id])
    @attachment.file.attach(params[:attachment][:file])

    if @attachment.save
      ProcessUploadedFileJob.perform_later(@attachment.id)

      render json: { success: true, attachment: { filename: @attachment.file.filename.to_s, state: @attachment.state } }, status: :created
    else
      render json: { success: false, errors: @attachment.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private
  def custom_inputs_params
    params.require(:custom_inputs).permit!
  end

  def amplifier_params
    params.require(:amplifier).permit(:title)
  end

  def message_params
    params.require(:amplifier_conversation).permit(:content, :conversation_id)
  end

  def find_amplifier
    @amplifier = current_user.amplifiers.find(params[:id])
  end
end

app/views/amplifiers/_amplifier.html.erb
<div class="row mb-4" id="amplifier_<%= amplifier.id %>">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="d-flex justify-content-between align-items-center mb-3">
          <h5 class="card-title mb-0"><%= amplifier.title %></h5>
          <div class="assignments" style="text-align: right;">
            <p class="btn btn-sm btn-success" style="cursor: default;">Assignments</p>
            <p><%= amplifier.amplifier_type.title %></p>
          </div>
        </div>
        <p class="card-text"><%= amplifier.description %></p>
        <div class="d-flex justify-content-between align-items-center">
          <small class="text-muted"><%= amplifier.created_at.strftime("%B %d, %Y") %></small>
          <div class="btn-group">
            <%= link_to "Edit", edit_amplifier_path(amplifier), class: "btn btn-sm btn-outline-primary" %>
            <%= link_to "Delete", amplifier_path(amplifier),
                data: {turbo_method: :delete, turbo_confirm: 'Are you sure'},
                class:"btn btn-sm btn-outline-danger" %>
            <% if amplifier.state == 'draft' %>
              <a href="#" class="btn btn-sm btn-outline-success">Publish</a>
            <% end %>
          </div>
        </div>
      </div>
      <div class="card-footer">
        <small class="text-muted"><%= amplifier.amplifier_conversations.count %> attachments</small>
      </div>
    </div>
  </div>
</div>

app/views/amplifiers/_attachment_list.html.erb
<% attachments.order(created_at: :asc).each do |attachment| %>
 <% if attachment.url.present? %>
   <li>
     <%= attachment.url %>
     <small class="<%= attachment.state == 'uploaded' ? 'text-warning' : (attachment.state == 'processed' ? 'text-success' : 'text-danger') %>">
       <%= attachment.state.humanize %>
     </small>
   </li>
 <% else %>
    <li>
      <%= attachment.file.blob.filename %>
      <small class="<%= attachment.state == 'uploaded' ? 'text-warning' : (attachment.state == 'processed' ? 'text-success' : 'text-danger') %>">
        <%= attachment.state.humanize %>
      </small>
    </li>
  <% end %>
<% end %>

app/views/amplifiers/_form_conversation.html.erb
<div id="partial-wrapper">
  <div id="conversation_form" class="conversation-form">
    <%= form_for [amplifier, conversation], url: create_conversation_amplifiers_path, method: :post, remote: true, data: { turbo: :true, controller: "reset-form", action: "turbo:submit-end->reset-form#reset"  } do |f| %>
      <%= f.label :content, "Message" %>
      <%= f.text_area :content, class: "form-control", rows: 3, id: "message_content", value: defined?(message) ? message : "", oninput: "wordCounter()" %>
      <div class="d-flex justify-content-between mt-2">
        <%= f.submit "Send", class: "btn btn-primary" %>
        <span id="word_counter">200 words remaining</span>
      </div>
      <%= f.hidden_field :user_id, value: user_id  %>
      <%= f.hidden_field :amplifier_id, value: amplifier.id %>
      <%= f.hidden_field :conversation_id, value: conversation.id %>
    <% end %>
  </div>
</div>

<script>
  function wordCounter() {
    const maxLength = 200;
    const messageContent = document.getElementById("message_content");
    const wordCounterElement = document.getElementById("word_counter");
    const submitButton = document.querySelector("input[type='submit']");
    const words = messageContent.value.trim().split(/\s+/);
    const wordCount = words.length === 1 && words[0] === "" ? 0 : words.length;

    const remainingWords = maxLength - wordCount;
    wordCounterElement.textContent = `${remainingWords} words remaining`;

    if (remainingWords <= 0) {
      const allowedWords = words.slice(0, maxLength).join(" ");
      messageContent.value = allowedWords;
      submitButton.disabled = true;
      wordCounterElement.style.color = "red";
    } else {
      submitButton.disabled = false;
      wordCounterElement.style.color = "";
    }
  }
</script>

app/views/amplifiers/_inputs.html.erb
<div id="partial-wrapper">
  <%= form_tag create_custom_conversation_amplifiers_path, method: :post, remote: true, data: { turbo: :true } do %>
    <% category.inputs.each do |input_name, input_type| %>
      <div class="form-group">
        <%= label_tag input_name, input_name.capitalize %>
        <% if input_type == "text_field" %>
          <%= text_field_tag "custom_inputs[#{input_name}]", nil, class: "form-control" %>
        <% elsif input_type == "textarea" %>
          <%= text_area_tag "custom_inputs[#{input_name}]", nil, class: "form-control" %>
        <% elsif input_type == "select" %>
          <!-- Replace 'options' with an array of options for the select input -->
          <%= select_tag "custom_inputs[#{input_name}]", options_for_select(options), class: "form-control" %>
        <% end %>
      </div>
    <% end %>
    <%= hidden_field_tag :conversation_id, conversation.id %>
    <%= hidden_field_tag :category_id, category.id %>
    <div style="margin-top: 16px;">
      <%= submit_tag "Submit", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/amplifiers/_pagination.html.erb
<div id="pagination">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/amplifiers/edit.html.erb
<style>
  #amplifier-title-saved {
    display: none;
    opacity: 0;
  }

  #amplifier-title-saved.show {
    display: block;
    opacity: 1;
    transition: opacity 0.3s ease-in-out; /* Add a transition for the opacity property */
  }
</style>

<body>
  <div class="py-5" >
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1 class="">Create Assignment</h1>
          <input type="hidden" id="amplifier_id" value="<%= @amplifier.id %>">
          <input type="hidden" id="conversation_id" value="<%= @conversation.id %>">

          <%= form_for @amplifier, url: amplifier_path(@amplifier), html: {method: "patch", 'data-turbo-action': "replace", id: "amplifier-form"} do |f| %>
            <div class="form-group">
              <%= f.label :title, "Amplifier Title:" %>
              <%= f.text_field :title, id: "amplifier-title", class: "form-control" %>
              <div id="amplifier-title-saved" class="text-success">Saved</div>
            </div>

            <div class="form-group" data-controller="amplifier">
              <%= f.label :attachment, "Attachment:" %>
              <%= f.file_field :attachment, accept: 'application/epub+zip,audio/mpeg,audio/mp4,audio/wav,video/mp4,video/webm,image/*,application/vnd.openxmlformats-officedocument.presentationml.presentation,text/csv,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/markdown,text/plain,application/pdf,audio/x-m4a', data: { action: 'change->amplifier#uploadAttachment' } %>
              <%= hidden_field_tag :amplifier_conversation_id, @conversation.id %>
              <%= turbo_stream_from 'attachment_list' %>
              <div id="attachment-list">
                <%= render partial: 'amplifiers/attachment_list', locals: { attachments: @conversation.attachments } %>
              </div>
            </div>
          <% end %>
          <%= form_tag upload_url_path, method: :post, id: "url-upload-form" do %>
            <div class="form-group">
              <%= label_tag "attachment[url]", "Attachment URL:" %>
              <%= text_field_tag "attachment[url]", nil, id: "attachment-url", class: "form-control" %>
            </div>
            <%= hidden_field_tag :amplifier_conversation_id, @conversation.id %>
            <%= submit_tag "Upload URL", class: "btn btn-primary" %>
          <% end %>
          
          <%= turbo_stream_from 'message_container' %>
          <div id="message-wrapper">
            <%= render partial: "amplifier_conversations/messages", locals: { amplifier: @amplifier, conversation: @conversation  } %>
          </div>
          <!-- <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <div>
                  <label for="export-dropdown">Export</label>
                </div>
                <div class="btn-group">
                  <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> To Docs </button>
                  <div class="dropdown-menu"> <a class="dropdown-item" href="#">Action</a>
                  </div>
                </div>
              </div>
              <div class="row mt-2 justify-content-end custom-button-group">
                  <div class="col-md-auto">
                      <a class="btn btn-primary d-inline-flex" href="#">Schedule</a>
                  </div>
                  <div class="col-md-auto">
                      <a class="btn btn-secondary" href="#">Publish</a>
                  </div>
              </div>
            </div>
          </div> -->
        </div>
        <div class="col-md-6" data-controller="messages">
          <h1 class="">Amplifier</h1>
          <div class="card mb-3">
            <div class="card-header">Amplifier Type</div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <%= label_tag :amplifier_type_id, "Amplifier Type" %>
                    <%= select_tag :amplifier_type_id, options_for_select(([AmplifierType.find_by(title: 'General')].compact.map { |type| [type.title.capitalize, type.id] } + AmplifierType.where.not(title: ['Unassigned', 'General']).order(:title).map{ |type| [type.title.capitalize, type.id] }), selected: @amplifier.amplifier_type_id), class: "form-control", id: "amplifier-type-dropdown" %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <%= label_tag :category_type_id, "Category Type" %>
                    <%= select_tag :category_type_id, options_for_select([]), class: "form-control", id: "category-type-dropdown" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <%= turbo_stream_from 'partial_wrapper' %>
          <div id="partial-wrapper">
            <%= render partial: "amplifiers/form_conversation", locals: { amplifier: @amplifier, conversation: @conversation, user_id: current_user.id } %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script>
    document.addEventListener('turbo:load', function() {
      const categoryTypeDropdown = document.getElementById('category-type-dropdown');
      const partialWrapper = document.getElementById('partial-wrapper');

      // Event listener for the change event on the category type dropdown
      categoryTypeDropdown.addEventListener("change", function() {
        // Update the value of the category_id hidden field
        categoryIdHiddenField = document.getElementById('category_id');
        categoryIdHiddenField.value = categoryTypeDropdown.value;
      });

      // Function to show or hide the partial based on the dropdown value
      function togglePartial() {
        let partialName = '';

        if (categoryTypeDropdown.textContent === 'General') {
          partialName = 'form_conversation'; // The partial to display when the value is 'some_value'
        } else {
          partialName = 'custom_inputs'; // The partial to display for other values
        }

        fetchPartial(partialName, categoryTypeDropdown.value);
      }

      // Function to fetch the partial and replace the existing one
      function fetchPartial(partialName, categoryTypeId) {
        const amplifierId = document.getElementById('amplifier_id').value;
        const conversationId = document.getElementById('conversation_id').value;
        fetch(`/get_partial?partial_name=${partialName}&category_type_id=${categoryTypeId}&amplifier_id=${amplifierId}&conversation_id=${conversationId}`, {
          headers: {
            'Accept': 'text/vnd.turbo-stream.html'
          }
        });
      }

      // Function to update category type dropdown
      function updateCategoryTypeDropdown(amplifierTypeId) {
        fetch("/amplifier_prompts?amplifier_type_id=" + amplifierTypeId)
          .then(response => response.json())
          .then(data => {
            var dropdown = document.getElementById("category-type-dropdown");
            var options = data.map(prompt => [prompt.title, prompt.id]);
            dropdown.innerHTML = optionsForSelect(options);
            togglePartial(); // Call the toggle function after updating the dropdown
          });
      }

      // Helper function to generate options for select tag
      function optionsForSelect(options) {
        return options.map(option => `<option value="${option[1]}">${option[0]}</option>`).join('');
      }

      // Listen for changes on the amplifier type dropdown
      document.getElementById("amplifier-type-dropdown").addEventListener("change", function() {
        updateCategoryTypeDropdown(this.value);
      });

      // Update the category type dropdown with the initial selection
      updateCategoryTypeDropdown(document.getElementById("amplifier-type-dropdown").value);
    });
  </script>
</body>

app/views/amplifiers/index.html.erb
<body>
  <div class="py-5" >
    <div class="container">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <h1 class="text-left">History</h1>
        <%= link_to 'Create New', new_amplifier_path, class: 'btn btn-primary' %>
      </div>
      <div class="row" id="amplifiers_list">
        <% @amplifiers.each do |amplifier| %>
          <%= render partial: "amplifier", locals: { amplifier: amplifier } %>
        <% end %>
      </div>
      <%= render partial: "pagination" %>
  </div>
 </div>
</body>

app/views/amplifiers/new.html.erb
<style>
  #amplifier-title-saved {
    display: none;
    opacity: 0;
  }

  #amplifier-title-saved.show {
    display: block;
    opacity: 1;
    transition: opacity 0.3s ease-in-out; /* Add a transition for the opacity property */
  }
</style>

<body>
  <div class="py-5" >
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1 class="">Create Assignment</h1>
          <%= form_for @amplifier, url: amplifier_path(@amplifier), html: {method: "patch", 'data-turbo-action': "replace", id: "amplifier-form"} do |f| %>
            <div class="form-group">
              <%= f.label :title, "Amplifier Title:" %>
              <%= f.text_field :title, id: "amplifier-title", class: "form-control" %>
              <div id="amplifier-title-saved" class="text-success">Saved</div>
            </div>
          <% end %>
          <%= render partial: "amplifier_conversations/messages", locals: { amplifier: @amplifier, conversation: AmplifierConversation.new(amplifier: @amplifier) } %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <div>
                  <label for="export-dropdown">Export</label>
                </div>
                <div class="btn-group">
                  <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> To Docs </button>
                  <div class="dropdown-menu"> <a class="dropdown-item" href="#">Action</a>
                  </div>
                </div>
              </div>
              <div class="row mt-2 justify-content-end custom-button-group">
                  <div class="col-md-auto">
                      <a class="btn btn-primary d-inline-flex" href="#">Schedule</a>
                  </div>
                  <div class="col-md-auto">
                      <a class="btn btn-secondary" href="#">Publish</a>
                  </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6" data-controller="messages">
          <h1 class="">Amplifier</h1>
          <%= render partial: "amplifiers/form_conversation", locals: { amplifier: @amplifier, conversation: @conversation } %>
          <div class="card mb-3">
            <div class="card-header"> Amplifier Type</div>
            <div class="card-body">
              <div class="btn-group">
                <div class="form-group">
                  <%= label_tag :amplifier_type_id, "Amplifier Type" %>
                  <%= select_tag :amplifier_type_id, options_for_select(AmplifierType.all.map{ |type| [type.title, type.id] }, selected: @amplifier.amplifier_type_id), class: "form-control" %>
                </div>
              </div>
              <p>Category Type</p>
              <div class="btn-group">
                <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> Dropdown </button>
                <div class="dropdown-menu"> <a class="dropdown-item" href="#">Action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Separated link</a>
                </div>
              </div>
            </div>
          </div>
          <div class="card">
            <div class="card-header"> Course Information</div>
            <div class="card-body">
              <p>Course</p>
              <div class="btn-group">
                <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> Math Second Grade </button>
                <div class="dropdown-menu"> <a class="dropdown-item" href="#">Action</a>
                </div>
              </div>
            </div>
            <div class="card-body">
              <p>Grade</p>
              <div class="btn-group">
                <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> Second Grade </button>
                <div class="dropdown-menu"> <a class="dropdown-item" href="#">Action</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>