config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    mount Sidekiq::Web => "/sidekiq"

    root "amplifiers#index", as: :authenticated_root
    get 'amplifiers/new', to: 'amplifiers#new_amplifier', as: 'new_amplifier'

    resources :amplifiers do
      post 'create_conversation', on: :collection
      post 'create_custom_conversation', on: :collection
      post 'attachments', on: :collection
    end
  end

  unauthenticated :user do
    root "pages#about", as: :unauthenticated_root
  end

  get "about", to: "pages#about"
  resources :amplifier_prompts, only: [:index]
  get 'get_partial', to: 'amplifier_prompts#get_partial'
  post 'upload_url', to: 'amplifiers#upload_url', as: 'upload_url'
end

app/views/layouts/_alerts.html.erb
<% if notice || alert%>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Amplifier", user_signed_in? ? authenticated_root_path : unauthenticated_root_path, class:'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", user_signed_in? ? authenticated_root_path : unauthenticated_root_path, class:'nav-link'%>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if current_user %>
          <li class="nav-item">
            <span class="nav-link"><%= current_user.email %></span>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-link nav-link", style: "padding: 0.5rem 1rem;" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class:'nav-link'%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'amplifier_edit' %>  </head>
  <body>
    <header>
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/alerts' %>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>